auto:	          true
markdown:         rdiscount
pygments:         true
paginate:         6
permalink:        /:title
title:            Wyvern's Blog
url:              http://imwyvern.com
author:
    name:         Wyvern
   weibo:     	   weibo.com/goonerwyvern
description:      "wyvern's Blog"
author_info:      <a href="http://imwyvern.com/about">wyvern</a>

copyright:
    - Design by <a href="http://imwyvern.com/" title="wyvern" target="_blank">wyvern</a> &copy; 2013